In [61]:
# =========================
# 1. Import Libraries
# =========================
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

# =========================
# 2. Load Dataset
# =========================
new_df = pd.read_csv("dataset_fraud.csv")
df=new_df.sample(5000)
df.to_csv("data.csv",index=False)

# =========================
# 3. Basic Inspection
# =========================
print(df.shape)
print(df.info())
print(df.isnull().sum())

# =========================
# 4. Drop Unnecessary Columns
# (IDs that don't help model)
# =========================
df = df.drop(["step","isFlaggedFraud","nameOrig", "nameDest"], axis=1)

# =========================
# 5. Feature Engineering
# =========================
# Balance difference features
df["orgBalanceDiff"] = df["oldbalanceOrg"] - df["newbalanceOrig"]
df["destBalanceDiff"] = df["newbalanceDest"] - df["oldbalanceDest"]

# =========================
# 6. Encode Categorical Feature
# =========================
le = LabelEncoder()
df["type"] = le.fit_transform(df["type"])

# =========================
# 7. Define Features and Target
# =========================
X = df.drop("isFraud", axis=1)
y = df["isFraud"]

# =========================
# 8. Train-Test Split
# =========================
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# =========================
# 9. Feature Scaling
# =========================
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Training data shape:", X_train_scaled.shape)
print("Testing data shape:", X_test_scaled.shape)

from imblearn.over_sampling import SMOTE

sm = SMOTE(random_state=42)
X_resampled, y_resampled = sm.fit_resample(X_train, y_train)

print("Before SMOTE:", y_train.value_counts())
print("After SMOTE:", pd.Series(y_resampled).value_counts())

from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=200,
    max_depth=12,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1)
rf.fit(X_resampled,y_resampled)

y_pred = rf.predict(X_test_scaled)
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

(5000, 11)
<class 'pandas.core.frame.DataFrame'>
Index: 5000 entries, 2422435 to 3257438
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   step            5000 non-null   int64  
 1   type            5000 non-null   object 
 2   amount          5000 non-null   float64
 3   nameOrig        5000 non-null   object 
 4   oldbalanceOrg   5000 non-null   float64
 5   newbalanceOrig  5000 non-null   float64
 6   nameDest        5000 non-null   object 
 7   oldbalanceDest  5000 non-null   float64
 8   newbalanceDest  5000 non-null   float64
 9   isFraud         5000 non-null   int64  
 10  isFlaggedFraud  5000 non-null   int64  
dtypes: float64(5), int64(3), object(3)
memory usage: 468.8+ KB
None
step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtyp

ValueError: Expected n_neighbors <= n_samples_fit, but n_neighbors = 6, n_samples_fit = 5, n_samples = 5

In [3]:
# =========================
# 1. Import Libraries
# =========================
import pandas as pd
import numpy as np
import gc

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    precision_recall_curve,
    auc
)

from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE
import joblib


# =========================
# 2. Load Dataset Efficiently
# =========================
df = pd.read_csv("dataset_fraud.csv", low_memory=True)

print("Original Dataset Shape:", df.shape)

# Reduce memory usage
for col in df.select_dtypes(include=["int64"]).columns:
    df[col] = df[col].astype("int32")

for col in df.select_dtypes(include=["float64"]).columns:
    df[col] = df[col].astype("float32")

print("Fraud Distribution:")
print(df["isFraud"].value_counts())


# =========================
# 3. Drop Unnecessary Columns
# =========================
df.drop(["step", "isFlaggedFraud", "nameOrig", "nameDest"], axis=1, inplace=True)


# =========================
# 4. Feature Engineering
# =========================
df["orgBalanceDiff"] = df["oldbalanceOrg"] - df["newbalanceOrig"]
df["destBalanceDiff"] = df["newbalanceDest"] - df["oldbalanceDest"]


# =========================
# 5. Encode Categorical
# =========================
le = LabelEncoder()
df["type"] = le.fit_transform(df["type"])


# =========================
# 6. Reduce Dataset Size (IMPORTANT)
# =========================
fraud = df[df.isFraud == 1]
non_fraud = df[df.isFraud == 0].sample(len(fraud) * 5, random_state=42)

df = pd.concat([fraud, non_fraud])
df.to_csv('data.csv')
print("Balanced Dataset Shape:", df.shape)


# =========================
# 7. Split Data
# =========================
X = df.drop("isFraud", axis=1)
y = df["isFraud"]

del df
gc.collect()

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


# =========================
# 8. SMOTE (Safe now)
# =========================
sm = SMOTE(random_state=42, k_neighbors=3)
X_resampled, y_resampled = sm.fit_resample(X_train, y_train)

print("After SMOTE:", pd.Series(y_resampled).value_counts())


# =========================
# 9. Scaling
# =========================
scaler = StandardScaler()

X_resampled = scaler.fit_transform(X_resampled)
X_test_scaled = scaler.transform(X_test)


# =========================
# 10. Train Model
# =========================
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=15,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

rf.fit(X_resampled, y_resampled)


# =========================
# 11. Predictions
# =========================
y_pred = rf.predict(X_test_scaled)
y_prob = rf.predict_proba(X_test_scaled)[:, 1]


# =========================
# 12. Evaluation
# =========================
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

roc = roc_auc_score(y_test, y_prob)
print("\nROC-AUC:", roc)

precision, recall, _ = precision_recall_curve(y_test, y_prob)
pr_auc = auc(recall, precision)
print("PR-AUC:", pr_auc)


# =========================
# 13. Threshold Tuning
# =========================
threshold = 0.3
y_pred_adjusted = (y_prob > threshold).astype(int)

print("\nAdjusted Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_adjusted))


# =========================
# 14. Feature Importance
# =========================
feature_importance = pd.DataFrame({
    "feature": X.columns,
    "importance": rf.feature_importances_
}).sort_values(by="importance", ascending=False)

print("\nTop Features:")
print(feature_importance.head(10))


# =========================
# 15. Save Model
# =========================
# joblib.dump(rf, "fraud_model.pkl")
# joblib.dump(scaler, "scaler.pkl")
# joblib.dump(le, "label_encoder.pkl")

# print("\nModel saved successfully!")

Original Dataset Shape: (6362620, 11)
Fraud Distribution:
isFraud
0    6354407
1       8213
Name: count, dtype: int64
Balanced Dataset Shape: (49278, 9)
After SMOTE: isFraud
0    32852
1    32852
Name: count, dtype: int64

Confusion Matrix:
[[8169   44]
 [  12 1631]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      1.00      8213
           1       0.97      0.99      0.98      1643

    accuracy                           0.99      9856
   macro avg       0.99      0.99      0.99      9856
weighted avg       0.99      0.99      0.99      9856


ROC-AUC: 0.999353488475843
PR-AUC: 0.9986641631598642

Adjusted Confusion Matrix:
[[8138   75]
 [   3 1640]]

Top Features:
           feature  importance
6   orgBalanceDiff    0.310188
2    oldbalanceOrg    0.199530
1           amount    0.133307
3   newbalanceOrig    0.122202
0             type    0.098480
7  destBalanceDiff    0.078893
5   newbalanceDest    0.031730
4   oldb

In [17]:
X = [[1,1000,1234,1200,200,3245,100,500]]

fraud_prob = rf.predict_proba(X)[0][1]
print(fraud_prob)
# threshold = 0.9

# if fraud_prob > threshold:
#     print("Fraud Transaction")
# else:
#     print("Legitimate Transaction")

0.345


In [22]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred = rf.predict(X_test_scaled)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 0 45]
 [ 0 55]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        45
           1       0.55      1.00      0.71        55

    accuracy                           0.55       100
   macro avg       0.28      0.50      0.35       100
weighted avg       0.30      0.55      0.39       100



d:\archit\mlops\Fraud-Detection-System--End-to-end-ml-project-\myvenv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
d:\archit\mlops\Fraud-Detection-System--End-to-end-ml-project-\myvenv\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\archit\mlops\Fraud-Detection-System--End-to-end-ml-project-\myvenv\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\archit\mlops\

In [23]:
print(y_train.value_counts())
print(y_test.value_counts())

isFraud
0    208
1    192
Name: count, dtype: int64
isFraud
1    55
0    45
Name: count, dtype: int64


In [32]:
rf.predict([[1,31953.5,1234,31953.5,0.0,3245,0.0,0]])

d:\archit\mlops\Fraud-Detection-System--End-to-end-ml-project-\myvenv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0])

In [2]:
import mlflow
import mlflow.sklearn
import dagshub

mlflow.set_tracking_uri('https://dagshub.com/ArchitSaki/Fraud-Detection-System--End-to-end-ml-project-.mlflow')
dagshub.init(repo_owner='ArchitSaki', repo_name='Fraud-Detection-System--End-to-end-ml-project-', mlflow=True)

d:\archit\mlops\Fraud-Detection-System--End-to-end-ml-project-\myvenv\lib\site-packages\requests\__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (6.0.0.post1)/charset_normalizer (3.4.4) doesn't match a supported version!
  warnings.warn(


Accessing as ArchitSaki

Initialized MLflow to track repo "ArchitSaki/Fraud-Detection-System--End-to-end-ml-project-"

Repository ArchitSaki/Fraud-Detection-System--End-to-end-ml-project- initialized!

In [5]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import  GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

model = RandomForestClassifier()

# Hyperparameter grid
param_grid = {
    "n_estimators": [100, 200, 300],
    "max_depth": [None, 10, 20, 30],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4]
}

# Grid Search
grid_search = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=5,
    n_jobs=-1,
    scoring="f1_weighted"
)

mlflow.set_experiment("Hyperparameter_Tuning")

with mlflow.start_run(run_name="RandomForest_GridSearch"):

    # Train GridSearch
    grid_search.fit(X_train, y_train)

    best_model = grid_search.best_estimator_

    # Predictions
    y_pred = best_model.predict(X_test)

    # Metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Log best parameters
    mlflow.log_params(grid_search.best_params_)

    # Log metrics
    mlflow.log_metric("accuracy", accuracy)
    mlflow.log_metric("precision", precision)
    mlflow.log_metric("recall", recall)
    mlflow.log_metric("f1_score", f1)

    # Log model
    mlflow.sklearn.log_model(best_model, "best_model")

    print("Best Parameters:", grid_search.best_params_)

2026/02/24 16:11:15 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/02/24 16:11:18 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html


Best Parameters: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}
🏃 View run RandomForest_GridSearch at: https://dagshub.com/ArchitSaki/Fraud-Detection-System--End-to-end-ml-project-.mlflow/#/experiments/2/runs/bbb8d6d70cd14afc9c3a2e834452da8e
🧪 View experiment at: https://dagshub.com/ArchitSaki/Fraud-Detection-System--End-to-end-ml-project-.mlflow/#/experiments/2
